import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Underbar from "@/app/search/Underbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 화면을 전체적으로 덮고 중앙 정렬하는 div */}
        <div className="bg-stone-400 w-screen h-screen flex justify-center items-center">
          {/* 너비 480px, 세로 정렬, 높이 전체로 확장 */}
          <div className="bg-white w-[480px] h-screen flex flex-col relative">
            {/* 스크롤이 적용될 영역 */}
            <div className="flex-1 overflow-auto p-4 pb-16">{children}</div>

            {/* 하단바 추가 (기존 회색 바 제거) */}
            <Underbar />
          </div>
        </div>
      </body>
    </html>
  );
}
