version: "3.8"
services:
  db:
    image: postgres:15
    container_name: chanstagram-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chanstagram
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password
      TZ: Asia/Seoul
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data
      - ./db/postgres/init:/docker-entrypoint-initdb.d
    command: 
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "client_encoding=UTF8"